### ISSUE TITLE
Cannot verify .

### ISSUE THREAD

**Issue by dipkasyap** [imjerrybao/WechatPayDemo-iOS#1]
I have a query about your api server . Do we have to implement WeChat payment related configuration on our server (backend) too ? I am a bit confused about the working flow (control follow and data flow ) of the payment procedure.  

I Assume 

    PayReq * request = [[PayReq alloc] init];
     request.partnerId = @ "10000100";
     request.prepayId = @ "1101000000140415649af9fc314aa427";
     request.package = @ "Sign = WXPay";
     request.nonceStr = @ "a462b76e7436e98e0ed6e13c64b4fd1c";
     //request.timeStamp = @ "1397527777";
     request.sign = @ "582282D72DD2B03AD892830965F428CB16E7A256";
     [WXApi sendReq: request];

executing this on button action  should invoke the wechat pay screen, Please provide some information i have been stocked on sdk integration.

**Comment by imjerrybao** [comment]
First, you need apply wechat pay;
second, you need backend support;
third, you need configure you ios app.

See here for details
https://pay.weixin.qq.com/wiki/doc/api/app/app_jw.php?chapter=8_1
https://pay.weixin.qq.com/wiki/doc/api/app/app_jw.php?chapter=9_1
https://pay.weixin.qq.com/wiki/doc/api/app/app_jw.php?chapter=11_1

**Comment by dipkasyap** [comment]
Thnks  for kind response.

**Comment by jmagdada** [comment]
Hello @imjerrybao and @dipkasyap, I tried integrate the wechatpay sdk and I also registered for wechat pay but I can't make this working. After sending request `[WXApi sendReq: request];` nothing happens. I already followed the setup instructions and i also tried the demo by placing my appid but still the same thing nothing happens. I dont know what I am missing. Hope you can help me. Thanks!
